# Generated by Django 6.0.3 on 2026-05-11 09:58

import django.db.models.deletion
import django.utils.timezone
import evidence.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='exhibits/%Y/%m/%d/', validators=[evidence.validators.validate_file_size, evidence.validators.validate_forensic_file_type])),
                ('original_hash', models.CharField(blank=True, editable=False, max_length=64, null=True)),
                ('mime_type', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('integrity_status', models.CharField(choices=[('PENDING', 'Not Yet Verified'), ('INTACT', 'Integrity Verified (Match)'), ('FAILED', 'TAMPERED OR CORRUPTED (Mismatch)')], default='PENDING', max_length=20)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('captured_at', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('device_info', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('location_data', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, editable=False, max_length=50, null=True)),
                ('resolution', models.CharField(blank=True, editable=False, max_length=50, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Digital Evidence Exhibits',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('UPLOAD', 'Evidence Uploaded'), ('VIEW', 'Evidence Viewed'), ('DOWNLOAD', 'Evidence Downloaded'), ('VERIFY', 'Hash Re-verified'), ('DELETE', 'Evidence Deleted')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.TextField(blank=True, null=True)),
                ('recorded_hash', models.CharField(blank=True, max_length=64)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='evidence.evidence')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['original_hash'], name='hash_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['-uploaded_at'], name='upload_date_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['integrity_status'], name='status_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-timestamp'], name='audit_time_idx'),
        ),
    ]
