# Generated by Django 6.0.3 on 2026-05-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_time_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('UPLOAD', 'Evidence Uploaded'), ('VIEW', 'Evidence Viewed'), ('DOWNLOAD', 'Evidence Downloaded'), ('VERIFY', 'Hash Re-verified'), ('DELETE', 'Evidence Deleted'), ('FORENSIC_EXTRACT', 'Metadata Extracted')], max_length=20),
        ),
    ]
