# Generated by Django 6.0.3 on 2026-05-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_remove_auditlog_audit_time_idx_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='tamper_details',
            field=models.TextField(blank=True, editable=False, help_text='Detailed forensic alerts regarding file modifications generated by the analysis engine.', null=True),
        ),
    ]
