# Generated by Django 6.0.3 on 2026-05-12 15:17

import evidence.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0003_evidence_tamper_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Priority in the list')),
            ],
            options={
                'verbose_name': 'Support FAQ',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='evidence',
            name='file_upload',
            field=models.FileField(blank=True, help_text='<div style="margin-top: 10px; color: #666; font-size: 0.85rem;"><strong>ACCEPTED FORENSIC FORMATS:</strong><br>• <b>Images:</b> .jpg, .png, .tiff, .raw<br>• <b>Video/Audio:</b> .mp4, .mov, .wav, .mp3<br>• <b>Documents:</b> .pdf, .docx, .txt, .csv<br>• <b>Archives:</b> .zip, .iso, .e01, .ad1</div>', null=True, upload_to='exhibits/%Y/%m/%d/', validators=[evidence.validators.validate_file_size, evidence.validators.validate_forensic_file_type]),
        ),
    ]
