import uuid
import magic
import hashlib
import datetime
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.core.exceptions import ValidationError
from django.db.models.signals import post_save
from django.dispatch import receiver

# Tools for hashing and stripping metadata (EXIF/Media) from files.
from .utils import calculate_sha256, get_exif_metadata, get_media_metadata
from .validators import validate_file_size, validate_forensic_file_type

# --- THE DIGITAL EXHIBIT VAULT ---

class Evidence(models.Model):
    """
    Core record for digital evidence. 
    Handles secure ingestion, hashing, and metadata mapping with strict file-lock management.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    
    # --- STORAGE & SECURITY VALIDATION ---
    # Updated with Help Text Guide for the Admin Panel
    file_upload = models.FileField(
        upload_to='exhibits/%Y/%m/%d/', 
        null=True, 
        blank=True,
        validators=[validate_file_size, validate_forensic_file_type],
        help_text=mark_safe(
            '<div style="margin-top: 10px; color: #666; font-size: 0.85rem;">'
            '<strong>ACCEPTED FORENSIC FORMATS:</strong><br>'
            '• <b>Images:</b> .jpg, .png, .tiff, .raw<br>'
            '• <b>Video/Audio:</b> .mp4, .mov, .wav, .mp3<br>'
            '• <b>Documents:</b> .pdf, .docx, .txt, .csv<br>'
            '• <b>Archives:</b> .zip, .iso, .e01, .ad1'
            '</div>'
        )
    )
    
    original_hash = models.CharField(max_length=64, blank=True, null=True, editable=False)
    mime_type = models.CharField(max_length=100, blank=True, null=True, editable=False)
    
    # --- LIVE INTEGRITY MONITORING ---
    INTEGRITY_CHOICES = [
        ('PENDING', 'Not Yet Verified'),
        ('INTACT', 'Integrity Verified (Match)'),
        ('FAILED', 'TAMPERED OR CORRUPTED (Mismatch)'),
    ]
    
    integrity_status = models.CharField(
        max_length=20, 
        choices=INTEGRITY_CHOICES, 
        default='PENDING'
    )
    last_verified_at = models.DateTimeField(null=True, blank=True)

    # DETAILED FORENSIC LOGGING
    tamper_details = models.TextField(
        blank=True, 
        null=True, 
        editable=False,
        help_text="Detailed forensic alerts regarding file modifications generated by the analysis engine."
    )

    # --- FORENSIC METADATA ---
    captured_at = models.CharField(max_length=100, blank=True, null=True, editable=False)
    device_info = models.CharField(max_length=255, blank=True, null=True, editable=False)
    location_data = models.CharField(max_length=255, blank=True, null=True, editable=False)
    duration = models.CharField(max_length=50, blank=True, null=True, editable=False)
    resolution = models.CharField(max_length=50, blank=True, null=True, editable=False)
    
    uploaded_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Digital Evidence Exhibits"
        indexes = [
            models.Index(fields=['original_hash'], name='hash_idx'),
            models.Index(fields=['-uploaded_at'], name='upload_date_idx'),
            models.Index(fields=['integrity_status'], name='status_idx'),
        ]

    def save(self, *args, **kwargs):
        """
        Saves the record and ensures the file is released immediately after hashing.
        """
        if self.file_upload and not self.original_hash:
            # 1. GENERATE HASH (Using chunks to avoid memory locks)
            sha256_hash = hashlib.sha256()
            
            for chunk in self.file_upload.chunks():
                sha256_hash.update(chunk)
            
            temp_hash = sha256_hash.hexdigest()

            # 2. DUPLICATE DETECTION
            duplicate = Evidence.objects.filter(original_hash=temp_hash).exclude(id=self.id).first()
            if duplicate:
                raise ValidationError(
                    f"Forensic Duplicate Detected: This exact file already exists as '{duplicate.title}'."
                )

            self.original_hash = temp_hash
            
            # 3. EXTRACT MIME TYPE (Safely closing the buffer via try/finally)
            try:
                self.file_upload.seek(0)
                header_data = self.file_upload.read(2048)
                self.mime_type = magic.from_buffer(header_data, mime=True)
            finally:
                self.file_upload.seek(0)

        super().save(*args, **kwargs)

    def check_integrity(self):
        """
        Manually re-verifies the file.
        """
        try:
            current_hash = calculate_sha256(self.file_upload)
            
            self.integrity_status = 'INTACT' if current_hash == self.original_hash else 'FAILED'
            self.last_verified_at = timezone.now()
            self.save(update_fields=['integrity_status', 'last_verified_at'])

            AuditLog.objects.create(
                evidence=self,
                user=None, 
                action='VERIFY',
                recorded_hash=current_hash,
                details=f"Manual Integrity Check. Result: {self.integrity_status}"
            )
            return self.integrity_status
        except Exception as e:
            return f"Verification Error: {str(e)}"

    def __str__(self):
        return f"{self.title} ({self.id})"

# --- THE AUDIT TRAIL ---

class AuditLog(models.Model):
    ACTION_CHOICES = [
        ('UPLOAD', 'Evidence Uploaded'),
        ('VIEW', 'Evidence Viewed'),
        ('DOWNLOAD', 'Evidence Downloaded'),
        ('VERIFY', 'Hash Re-verified'),
        ('DELETE', 'Evidence Deleted'),
        ('FORENSIC_EXTRACT', 'Metadata Extracted'),
    ]

    evidence = models.ForeignKey(Evidence, on_delete=models.SET_NULL, null=True, related_name='audit_logs')
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    action = models.CharField(max_length=20, choices=ACTION_CHOICES)
    ip_address = models.GenericIPAddressField(null=True, blank=True)
    timestamp = models.DateTimeField(default=timezone.now)
    details = models.TextField(blank=True, null=True)
    recorded_hash = models.CharField(max_length=64, blank=True)

    class Meta:
        ordering = ['-timestamp']

# --- SUPPORT & KNOWLEDGE BASE ---

class SupportFaq(models.Model):
    """
    Model to store and manage the platform's Help & FAQ content.
    """
    question = models.CharField(max_length=255)
    answer = models.TextField()
    order = models.PositiveIntegerField(default=0, help_text="Priority in the list")

    class Meta:
        verbose_name = "Support FAQ"
        ordering = ['order']

    def __str__(self):
        return self.question

# --- AUTOMATIC SIGNAL RECEIVER ---

@receiver(post_save, sender=Evidence)
def auto_verify_and_extract(sender, instance, created, **kwargs):
    """
    Post-save forensic processing. 
    """
    if created and instance.file_upload:
        try:
            update_data = {}
            file_path = instance.file_upload.path

            if instance.mime_type and 'image' in instance.mime_type:
                meta = get_exif_metadata(instance.file_upload)
                update_data = {
                    'captured_at': meta.get('date_time'),
                    'device_info': meta.get('device'),
                    'location_data': meta.get('gps')
                }
            
            elif instance.mime_type and ('video' in instance.mime_type or 'audio' in instance.mime_type):
                media = get_media_metadata(file_path)
                update_data = {
                    'duration': media.get('duration'),
                    'resolution': media.get('resolution')
                }

            if update_data:
                Evidence.objects.filter(id=instance.id).update(**update_data)

            AuditLog.objects.create(
                evidence=instance,
                user=instance.uploaded_by,
                action='UPLOAD',
                recorded_hash=instance.original_hash,
                details=f"Automatic Forensic Ingestion. Hash verified: {instance.original_hash}"
            )

        except Exception as e:
            print(f"Automated Forensic Error: {e}")